version: "3.8"

services:
  web:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./site:/usr/share/nginx/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    volumes:
      - ./db:/var/lib/mysql
